name: Backend CI
on:
  push:
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cd backend && npm install && npm run start
